# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# APIs
yacl_version=3.9.7+26.3-fabric
modmenu_version=21.0.0

# Mod Properties
mod_version=1.2.0
maven_group=vorez.mods.skins
archives_base_name=offlineskins-reloaded-26.3-fabric

# Dependencies
fabric_api_version=0.162.0+26.3
